Repository woowacourse-teams/2020-taggle, pull requests merged in 2020-08, with the labels that each got.

#107 feat(bookmark-read-api): 북마크 조회 페이지 API 연동
  backend/web/src/frontend/.eslintrc.js
  backend/web/src/frontend/package-lock.json
  backend/web/src/frontend/package.json
  backend/web/src/frontend/src/api/index.js
  backend/web/src/frontend/src/api/module/bookmark.js
  backend/web/src/frontend/src/store/index.js
  backend/web/src/frontend/src/store/share/actionType.js
  backend/web/src/frontend/src/store/share/mutationsType.js
  backend/web/src/frontend/src/views/bookmark/components/BookmarkCard.vue
  backend/web/src/main/java/com/woowacourse/taggle/HomeController.java
  backend/web/src/test/java/com/woowacourse/taggle/security/config/WebSecurityConfigTest.java
Labels: :computer:FE

#112 refactor(frontend): 디자인 개선 및 mock data 정리 (#105)
  backend/web/build.gradle
  backend/web/src/frontend/.eslintrc.js
  backend/web/src/frontend/.prettierrc.js
  backend/web/src/frontend/babel.config.js
  backend/web/src/frontend/package-lock.json
  backend/web/src/frontend/package.json
  backend/web/src/frontend/src/App.vue
  backend/web/src/frontend/src/main.js
  backend/web/src/frontend/src/plugins/vuetify.js
  backend/web/src/frontend/src/router/index.js
  backend/web/src/frontend/src/router/modules/bookmark.js
  backend/web/src/frontend/src/store/index.js
  backend/web/src/frontend/src/utils/mockTags.js
  backend/web/src/frontend/src/views/bookmark/components/BookmarkCard.vue
  backend/web/src/frontend/src/views/bookmark/components/CardModule.vue
  backend/web/src/frontend/src/views/bookmark/components/CardStream.vue
  backend/web/src/frontend/src/views/header/BookmarkHeader.vue
  backend/web/src/frontend/src/views/header/components/TagList.vue
  backend/web/src/frontend/vue.config.js
Labels: :computer:FE, :hammer_and_wrench:리팩토링, :star::star::star:

#113 feat(category): Tag에 Catagory 필드 추가 (#53)
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/Category.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/CategoryRepository.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/Tag.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/BookmarkTagResponse.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/CategoryDetailResponse.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/CategoryRequest.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/CategoryResponse.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/exception/CategoryDuplicationException.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/exception/CategoryNotFoundException.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/CategoryService.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/TagBookmarkService.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/TagService.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/domain/CategoryTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/CategoryServiceTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/TagBookmarkServiceTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/TagServiceTest.java
  backend/web/src/docs/asciidoc/api-guide.adoc
  backend/web/src/main/java/com/woowacourse/taggle/tag/controller/CategoryController.java
  backend/web/src/main/java/com/woowacourse/taggle/tag/controller/TagController.java
  backend/web/src/test/java/com/woowacourse/taggle/ControllerTest.java
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/AcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/BookmarkAcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/CategoryAcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/TagAcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/setup/domain/CategorySetup.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/CategoryControllerTest.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/TagControllerTest.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/docs/CategoryDocumentation.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/docs/TagDocumentation.java
Labels: :computer:BE

#125 feat(frontend): 태그 목록에 태그 검색, 추가, 수정 레이아웃 작업 (#121)
  backend/web/src/frontend/package-lock.json
  backend/web/src/frontend/package.json
  backend/web/src/frontend/src/views/header/BookmarkHeader.vue
  backend/web/src/frontend/src/views/header/component/CategoryAddModal.vue
  backend/web/src/frontend/src/views/header/component/TagEditModal.vue
Labels: :computer:FE

#131 feat(backend): Category, Tag, Bookmark에 Member 연결 (#104)
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/Bookmark.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/BookmarkRepository.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/Category.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/CategoryRepository.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/Tag.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/TagRepository.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/BookmarkCreateRequest.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/BookmarkTagResponse.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/CategoryDetailResponse.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/CategoryRequest.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/CategoryTagsResponse.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/TagCreateRequest.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/exception/CategoryDuplicationException.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/BookmarkService.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/CategoryService.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/TagBookmarkService.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/TagService.java
  backend/core/src/main/java/com/woowacourse/taggle/user/domain/User.java
  backend/core/src/main/java/com/woowacourse/taggle/user/domain/UserRepository.java
  backend/core/src/main/java/com/woowacourse/taggle/user/dto/OAuthAttributes.java
  backend/core/src/main/java/com/woowacourse/taggle/user/dto/SessionUser.java
  backend/core/src/main/java/com/woowacourse/taggle/user/exception/UserNotFoundException.java
  backend/core/src/main/java/com/woowacourse/taggle/user/service/UserService.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/domain/BookmarkTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/domain/CategoryTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/domain/TagTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/BookmarkServiceTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/CategoryServiceTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/TagBookmarkServiceTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/TagServiceTest.java
  backend/core/src/test/java/com/woowacourse/taggle/user/domain/UserRepositoryTest.java
  backend/web/src/docs/asciidoc/api-guide.adoc
  backend/web/src/main/java/com/woowacourse/taggle/authentication/UserArgumentResolver.java
  backend/web/src/main/java/com/woowacourse/taggle/security/config/UserConfig.java
  backend/web/src/main/java/com/woowacourse/taggle/security/config/WebSecurityConfig.java
  backend/web/src/main/java/com/woowacourse/taggle/security/service/CustomOAuth2UserService.java
  backend/web/src/main/java/com/woowacourse/taggle/tag/controller/ApiControllerAdvice.java
  backend/web/src/main/java/com/woowacourse/taggle/tag/controller/BookmarkController.java
  backend/web/src/main/java/com/woowacourse/taggle/tag/controller/CategoryController.java
  backend/web/src/main/java/com/woowacourse/taggle/tag/controller/TagController.java
  backend/web/src/test/java/com/woowacourse/taggle/ControllerTest.java
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/AcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/BookmarkAcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/CategoryAcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/TagAcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/setup/domain/BookmarkSetup.java
  backend/web/src/test/java/com/woowacourse/taggle/setup/domain/CategorySetup.java
  backend/web/src/test/java/com/woowacourse/taggle/setup/domain/TagSetup.java
  backend/web/src/test/java/com/woowacourse/taggle/setup/domain/UserSetup.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/BookmarkControllerTest.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/CategoryControllerTest.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/TagControllerTest.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/docs/BookmarkDocumentation.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/docs/CategoryDocumentation.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/docs/TagDocumentation.java
Labels: :computer:BE

#150 fix(config): oauth2 로그인 요청에 대한 proxy 설정 추가 (#149)
  backend/web/src/frontend/vue.config.js
Labels: :computer:FE

#157 fix(category): uncategorized tag의 id가 null인 경우 문서화 테스트 실패하는 문제 해결 (#119)
  backend/web/src/test/java/com/woowacourse/taggle/setup/domain/CategorySetup.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/CategoryControllerTest.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/docs/CategoryDocumentation.java
Labels: :computer:BE

#151 fix(backend): 같은 이름의 카테고리, 태그, 북마크 엔티티 중복 생성 되지 않도록 수정 (#148)
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/BookmarkService.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/CategoryService.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/TagService.java
  backend/core/src/test/java/com/woowacourse/taggle/fixture/UserFixture.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/domain/BookmarkTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/domain/CategoryTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/domain/TagTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/BookmarkServiceTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/CategoryServiceTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/TagBookmarkServiceTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/TagServiceTest.java
  backend/core/src/test/java/com/woowacourse/taggle/user/domain/UserRepositoryTest.java
  backend/web/src/docs/asciidoc/api-guide.adoc
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/BookmarkAcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/CategoryAcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/TagAcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/setup/domain/UserSetup.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/docs/BookmarkDocumentation.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/docs/TagDocumentation.java
Labels: :computer:BE, :hammer_and_wrench:리팩토링, 🚨버그

#152 fix(backend): put, delete 메소드 cors 허용 설정 변경 (#147)
  backend/web/src/main/java/com/woowacourse/taggle/security/config/WebSecurityConfig.java
Labels: :computer:BE, 🚨버그

#156 feat(backend): 태그가 없는 북마크 조회 추가 (#153)
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/Bookmark.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/TagBookmarkResponse.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/BookmarkService.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/TagBookmarkService.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/TagService.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/domain/TagBookmarkTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/BookmarkServiceTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/TagBookmarkServiceTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/TagServiceTest.java
  backend/web/src/docs/asciidoc/api-guide.adoc
  backend/web/src/main/java/com/woowacourse/taggle/tag/controller/BookmarkController.java
  backend/web/src/main/java/com/woowacourse/taggle/tag/controller/TagBookmarkController.java
  backend/web/src/main/java/com/woowacourse/taggle/tag/controller/TagController.java
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/AcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/BookmarkAcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/CategoryAcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/TagAcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/acceptance/TagBookmarkAcceptanceTest.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/BookmarkControllerTest.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/CategoryControllerTest.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/TagBookmarkControllerTest.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/TagControllerTest.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/docs/BookmarkDocumentation.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/docs/TagBookmarkDocumentation.java
  backend/web/src/test/java/com/woowacourse/taggle/tag/controller/docs/TagDocumentation.java
Labels: :computer:BE

#182 fix(bookmarks): 북마크 조회 페이지 수정 (#177)
  backend/web/src/frontend/src/api/module/tag.js
  backend/web/src/frontend/src/views/bookmark/components/BookmarkCard.vue
  backend/web/src/frontend/src/views/bookmark/components/CardModule.vue
  backend/web/src/frontend/src/views/bookmark/components/CardModuleItem.vue
  backend/web/src/frontend/src/views/bookmark/components/CardStreamItem.vue
Labels: :computer:FE, 🚨버그

#191 feat(tags): 태그 검색 기능 구현 (#160)
  backend/web/src/frontend/src/api/module/category.js
  backend/web/src/frontend/src/api/module/tag.js
  backend/web/src/frontend/src/store/modules/category.js
  backend/web/src/frontend/src/store/share/actionTypes.js
  backend/web/src/frontend/src/store/share/getterTypes.js
  backend/web/src/frontend/src/utils/constants.js
  backend/web/src/frontend/src/utils/validator.js
  backend/web/src/frontend/src/views/header/BookmarkHeader.vue
  backend/web/src/frontend/src/views/header/component/CategoryAddModal.vue
  backend/web/src/frontend/src/views/header/component/CategoryGroup.vue
  backend/web/src/frontend/src/views/header/component/CategorySubGroup.vue
  backend/web/src/frontend/src/views/header/component/TagEditModal.vue
  backend/web/src/frontend/src/views/header/component/TagNavigation.vue
  backend/web/src/frontend/src/views/header/component/TagNavigationBody.vue
  backend/web/src/frontend/src/views/header/component/TagNavigationFooter.vue
  backend/web/src/frontend/src/views/header/component/category/CategoryAddModal.vue
  backend/web/src/frontend/src/views/header/component/category/CategoryContextMenu.vue
  backend/web/src/frontend/src/views/header/component/category/CategoryEditModal.vue
  backend/web/src/frontend/src/views/header/component/category/CategoryIcons.vue
  backend/web/src/frontend/src/views/header/component/category/ContextMenu.vue
  backend/web/src/frontend/src/views/header/component/category/TagContextMenu.vue
  backend/web/src/frontend/src/views/main/component/BookmarkAddModal.vue
  backend/web/src/frontend/src/views/main/component/Snackbar.vue
Labels: :computer:FE

#197 feat(frontend): 카테고리, 태그 네비게이션 바 화면 개발, api 연동 (#196)
  backend/web/src/frontend/src/api/module/bookmark.js
  backend/web/src/frontend/src/api/module/category.js
  backend/web/src/frontend/src/api/module/tag.js
  backend/web/src/frontend/src/store/modules/bookmarkWithTags.js
  backend/web/src/frontend/src/store/modules/category.js
  backend/web/src/frontend/src/store/modules/tagWithBookmarks.js
  backend/web/src/frontend/src/store/share/actionTypes.js
  backend/web/src/frontend/src/store/share/getterTypes.js
  backend/web/src/frontend/src/store/share/mutationTypes.js
  backend/web/src/frontend/src/utils/constants.js
  backend/web/src/frontend/src/utils/validator.js
  backend/web/src/frontend/src/views/bookmark/BookmarkPage.vue
  backend/web/src/frontend/src/views/bookmark/component/BookmarkCard.vue
  backend/web/src/frontend/src/views/bookmark/component/CardIcons.vue
  backend/web/src/frontend/src/views/bookmark/component/CardModule.vue
  backend/web/src/frontend/src/views/bookmark/component/CardModuleItem.vue
  backend/web/src/frontend/src/views/bookmark/component/CardStream.vue
  backend/web/src/frontend/src/views/bookmark/component/CardStreamItem.vue
  backend/web/src/frontend/src/views/bookmark/component/TagEditModal.vue
  backend/web/src/frontend/src/views/bookmark/components/CardIcons.vue
  backend/web/src/frontend/src/views/common/component/ConfirmDialog.vue
  backend/web/src/frontend/src/views/header/component/CategoryGroup.vue
  backend/web/src/frontend/src/views/header/component/TagEditModal.vue
  backend/web/src/frontend/src/views/header/component/TagNavigationBody.vue
  backend/web/src/frontend/src/views/header/component/category/CategoryAddModal.vue
  backend/web/src/frontend/src/views/header/component/category/CategoryContextMenu.vue
  backend/web/src/frontend/src/views/header/component/category/CategoryEditModal.vue
  backend/web/src/frontend/src/views/header/component/category/ContextMenu.vue
  backend/web/src/frontend/src/views/header/component/category/TagContextMenu.vue
  backend/web/src/frontend/src/views/main/component/BookmarkAddModal.vue
Labels: :computer:FE, :hammer_and_wrench:리팩토링, 🛠기능
