Repository woowacourse-teams/2020-taggle, pull requests merged in 2020-07, with the labels that each got.

#33 chore: 프로젝트 모듈 분리
  backend/admin/build.gradle
  backend/admin/src/main/java/com/woowacourse/taggle/empty.txt
  backend/admin/src/test/java/com/woowacourse/taggle/empty.txt
  backend/build.gradle
  backend/core/build.gradle
  backend/core/src/main/java/com/wooacourse/taggle/Member.java
  backend/core/src/test/java/com/wooacourse/taggle/empty.txt
  backend/settings.gradle
  backend/src/main/resources/application.properties
  backend/web/build.gradle
  backend/web/src/main/java/com/woowacourse/taggle/WebApplication.java
  backend/web/src/main/java/com/woowacourse/taggle/controller/MemberController.java
  backend/web/src/test/java/com/woowacourse/taggle/WebApplicationTest.java
Labels: back-end

#44 feat: 태그 추가, 제거 및 북마크 추가, 제거 기능 구현 (#11, #12, #14, #15, #17)
  backend/core/src/main/java/com/woowacourse/taggle/common/config/JpaAuditingConfig.java
  backend/core/src/main/java/com/woowacourse/taggle/common/domain/BaseTimeEntity.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/Bookmark.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/BookmarkRepository.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/Tag.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/TagBookmark.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/TagBookmarkRepository.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/TagRepository.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/BookmarkCreateRequest.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/BookmarkCreateResponse.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/BookmarkRequest.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/BookmarkResponse.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/TagBookmarkRequest.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/TagBookmarkResponse.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/TagCreateRequest.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/dto/TagRequest.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/exception/BookmarkNotFoundException.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/exception/TagBookmarkNotFoundException.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/exception/TagNotFoundException.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/BookmarkService.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/TagBookmarkService.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/TagService.java
  backend/core/src/main/java/com/woowacourse/taggle/user/domain/Role.java
  backend/core/src/main/java/com/woowacourse/taggle/user/domain/User.java
  backend/core/src/test/java/com/woowacourse/taggle/JpaTestConfiguration.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/domain/BookmarkTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/domain/TagTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/BookmarkServiceTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/TagBookmarkServiceTest.java
  backend/core/src/test/java/com/woowacourse/taggle/tag/service/TagServiceTest.java
  backend/core/src/test/java/com/woowacourse/taggle/user/domain/UserRepositoryTest.java
  backend/core/src/test/resources/application-test.properties
  backend/web/src/main/java/com/woowacourse/taggle/WebApplication.java
  backend/web/src/main/java/com/woowacourse/taggle/security/config/WebSecurityConfig.java
  backend/web/src/main/java/com/woowacourse/taggle/security/dto/OAuthAttributes.java
  backend/web/src/main/java/com/woowacourse/taggle/security/dto/SessionUser.java
  backend/web/src/main/java/com/woowacourse/taggle/security/service/CustomOAuth2UserService.java
Labels: :computer:BE, :star::star::star:, 🛠기능

#64 chore : 프로젝트 루트 경로에 gitignore 추가 (#63)
  .gitignore
Labels: 🛠기능

#50 feat(frontend): 크롬익스텐션 기본 디자인 구성 (#49)
  taggle-extension/.babelrc
  taggle-extension/.eslintrc.js
  taggle-extension/.gitignore
  taggle-extension/.prettierrc
  taggle-extension/package-lock.json
  taggle-extension/package.json
  taggle-extension/scripts/build-zip.js
  taggle-extension/src/assets/hashtag-1320568266489631024_24.png
  taggle-extension/src/background.js
  taggle-extension/src/components/Buttons.vue
  taggle-extension/src/components/TagInput.vue
  taggle-extension/src/icons/icon.xcf
  taggle-extension/src/icons/icon_128.png
  taggle-extension/src/icons/icon_48.png
  taggle-extension/src/manifest.json
  taggle-extension/src/plugins/vuetify.js
  taggle-extension/src/popup/App.vue
  taggle-extension/src/popup/popup.html
  taggle-extension/src/popup/popup.js
  taggle-extension/webpack.config.js
Labels: :computer:FE

#62 feat(backend): springboot-logback설정 (#61)
  backend/build.gradle
  backend/web/src/main/resources/application.yml
  backend/web/src/main/resources/logback-local.xml
  backend/web/src/main/resources/logback-prod.xml
Labels: :computer:infra

#69 chore(frontend): ESLint 및 prettier 설정 (#25)
  frontend/.eslintrc.js
  frontend/.prettierrc.js
  frontend/package-lock.json
  frontend/package.json
Labels: :computer:FE

#51 feat(frontend): 북마크 관련 개인 페이지 구현 (#47)
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.vue
  frontend/src/assets/empty.txt
  frontend/src/assets/images/TaggleLog.png
  frontend/src/components/Home.vue
  frontend/src/main.js
  frontend/src/plugins/vuetify.js
  frontend/src/router/index.js
  frontend/src/router/modules/bookmark.js
  frontend/src/utils/mockTags.js
  frontend/src/views/bookmark/BookmarkPage.vue
  frontend/src/views/bookmark/components/BookmarkCard.vue
  frontend/src/views/bookmark/components/CardModule.vue
  frontend/src/views/bookmark/components/CardStream.vue
  frontend/src/views/empty.txt
  frontend/src/views/header/BookmarkHeader.vue
  frontend/src/views/header/components/TagList.vue
  frontend/vue.config.js
  taggle-extension/.babelrc
Labels: :computer:FE

#80 feat(chrome-extension): 크롬 익스텐션 북마크 추가, 삭제 기능 (#78)
  taggle-extension/src/api/index.js
  taggle-extension/src/api/module/bookmark.js
  taggle-extension/src/api/module/tag.js
  taggle-extension/src/api/module/tagBookmark.js
  taggle-extension/src/components/Buttons.vue
  taggle-extension/src/components/TagInput.vue
  taggle-extension/src/manifest.json
  taggle-extension/src/popup/App.vue
Labels: :computer:FE

#83 chore(backend): Spring boot, vue 통합 배포 설정 (#58)
  backend/.gitignore
  backend/build.gradle
  backend/web/build.gradle
  backend/web/src/frontend/.browserslistrc
  backend/web/src/frontend/.eslintrc.js
  backend/web/src/frontend/.gitignore
  backend/web/src/frontend/.prettierrc.js
  backend/web/src/frontend/README.md
  backend/web/src/frontend/babel.config.js
  backend/web/src/frontend/package-lock.json
  backend/web/src/frontend/package.json
  backend/web/src/frontend/public/index.html
  backend/web/src/frontend/src/App.vue
  backend/web/src/frontend/src/assets/images/TaggleLog.png
  backend/web/src/frontend/src/main.js
  backend/web/src/frontend/src/plugins/vuetify.js
  backend/web/src/frontend/src/router/index.js
  backend/web/src/frontend/src/router/modules/bookmark.js
  backend/web/src/frontend/src/store/index.js
  backend/web/src/frontend/src/utils/mockTags.js
  backend/web/src/frontend/src/views/bookmark/BookmarkPage.vue
  backend/web/src/frontend/src/views/bookmark/components/BookmarkCard.vue
  backend/web/src/frontend/src/views/bookmark/components/CardModule.vue
  backend/web/src/frontend/src/views/bookmark/components/CardStream.vue
  backend/web/src/frontend/src/views/header/BookmarkHeader.vue
  backend/web/src/frontend/src/views/header/components/TagList.vue
  backend/web/src/frontend/vue.config.js
  backend/web/src/main/java/com/woowacourse/taggle/HomeController.java
  backend/web/src/main/java/com/woowacourse/taggle/security/config/WebSecurityConfig.java
  frontend/src/main.js
  frontend/src/plugins/vuetify.js
  frontend/vue.config.js
Labels: :computer:infra
