Repository woowacourse-teams/2020-taggle, pull requests merged in 2020-09, with the labels that each got.

#217 fix(tag): 태그를 항상 삭제할 수 있도록 수정 (#216)
  backend/core/src/main/java/com/woowacourse/taggle/tag/domain/TagBookmarkRepository.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/BookmarkService.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/CategoryService.java
  backend/core/src/main/java/com/woowacourse/taggle/tag/service/TagService.java
Labels: :computer:BE, :star::star::star:, 🚨버그

#246 refactor(uri): api uri 구조 변경 (#231)
  backend/taggle-core/src/main/java/kr/taggle/bookmark/dto/BookmarkDetailResponse.java
  backend/taggle-core/src/main/java/kr/taggle/bookmark/dto/TagDetailResponse.java
  backend/taggle-core/src/main/java/kr/taggle/bookmark/service/BookmarkService.java
  backend/taggle-core/src/main/java/kr/taggle/bookmark/service/TagBookmarkService.java
  backend/taggle-core/src/main/java/kr/taggle/category/service/CategoryService.java
  backend/taggle-core/src/main/java/kr/taggle/tag/dto/CategoryDetailResponse.java
  backend/taggle-core/src/main/java/kr/taggle/tag/dto/TagUpdateRequest.java
  backend/taggle-core/src/main/java/kr/taggle/tag/service/TagService.java
  backend/taggle-core/src/test/java/kr/taggle/bookmark/service/TagBookmarkServiceTest.java
  backend/taggle-core/src/test/java/kr/taggle/category/service/CategoryServiceTest.java
  backend/taggle-core/src/test/java/kr/taggle/tag/service/TagServiceTest.java
  backend/taggle-web/src/docs/asciidoc/api-guide.adoc
  backend/taggle-web/src/main/java/kr/taggle/bookmark/controller/BookmarkController.java
  backend/taggle-web/src/main/java/kr/taggle/bookmark/controller/TagBookmarkController.java
  backend/taggle-web/src/main/java/kr/taggle/category/controller/CategoryController.java
  backend/taggle-web/src/main/java/kr/taggle/security/config/WebSecurityConfig.java
  backend/taggle-web/src/main/java/kr/taggle/tag/controller/TagController.java
  backend/taggle-web/src/main/java/kr/taggle/user/controller/UserController.java
  backend/taggle-web/src/test/java/kr/taggle/ControllerTest.java
  backend/taggle-web/src/test/java/kr/taggle/acceptance/CategoryAcceptanceTest.java
  backend/taggle-web/src/test/java/kr/taggle/acceptance/TagAcceptanceTest.java
  backend/taggle-web/src/test/java/kr/taggle/acceptance/TagBookmarkAcceptanceTest.java
  backend/taggle-web/src/test/java/kr/taggle/bookmark/controller/BookmarkControllerTest.java
  backend/taggle-web/src/test/java/kr/taggle/bookmark/controller/TagBookmarkControllerTest.java
  backend/taggle-web/src/test/java/kr/taggle/bookmark/docs/BookmarkDocumentation.java
  backend/taggle-web/src/test/java/kr/taggle/bookmark/docs/TagBookmarkDocumentation.java
  backend/taggle-web/src/test/java/kr/taggle/category/controller/CategoryControllerTest.java
  backend/taggle-web/src/test/java/kr/taggle/category/docs/CategoryDocumentation.java
  backend/taggle-web/src/test/java/kr/taggle/tag/controller/TagControllerTest.java
  backend/taggle-web/src/test/java/kr/taggle/tag/docs/TagDocumentation.java
  backend/taggle-web/src/test/java/kr/taggle/user/controller/UserControllerTest.java
  backend/taggle-web/src/test/java/kr/taggle/user/controller/docs/UserDocumentation.java
  backend/taggle-web/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  backend/taggle-web/src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
  frontend/src/api/module/bookmark.js
  frontend/src/api/module/category.js
  frontend/src/api/module/tag.js
  frontend/src/api/module/user.js
  frontend/src/router/modules/bookmark.js
  frontend/src/store/modules/bookmarkWithTags.js
  frontend/src/store/modules/category.js
  frontend/src/store/modules/tagWithBookmarks.js
  frontend/src/store/modules/user.js
  frontend/src/store/share/actionTypes.js
  frontend/src/store/share/getterTypes.js
  frontend/src/views/bookmark/component/TagEditModal.vue
  frontend/src/views/header/component/CategoryGroup.vue
  frontend/src/views/header/component/category/CategoryEditModal.vue
  frontend/src/views/main/component/BookmarkAddModal.vue
Labels: :hammer_and_wrench:리팩토링

#258 fix(uri): api 권한 확인용 api uri 오탈자 수정 (/api/v1//me -> /api/v1/me)
  backend/taggle-web/src/main/java/kr/taggle/security/config/WebSecurityConfig.java
Labels: :computer:BE, 🚨버그

#247 feat: 비즈니스 검증 로직 추가 (#227)
  backend/taggle-core/build.gradle
  backend/taggle-core/src/main/java/kr/taggle/category/domain/Category.java
  backend/taggle-core/src/main/java/kr/taggle/category/dto/CategoryRequest.java
  backend/taggle-core/src/main/java/kr/taggle/tag/domain/Tag.java
  backend/taggle-core/src/main/java/kr/taggle/tag/dto/TagCreateRequest.java
  backend/taggle-core/src/main/resources/application.yml
  backend/taggle-core/src/main/resources/messages.yml
  backend/taggle-web/src/main/java/kr/taggle/common/config/ValidationMessageConfig.java
  backend/taggle-web/src/main/java/kr/taggle/common/controller/ApiControllerAdvice.java
  backend/taggle-web/src/main/resources/db/migration/V2__modify_size.sql
  backend/taggle-web/src/test/java/kr/taggle/ControllerTest.java
  backend/taggle-web/src/test/java/kr/taggle/category/controller/CategoryControllerTest.java
  backend/taggle-web/src/test/java/kr/taggle/tag/controller/TagControllerTest.java
  frontend/src/store/modules/bookmarkWithTags.js
  frontend/src/store/share/getterTypes.js
  frontend/src/utils/validator.js
  frontend/src/views/bookmark/component/TagEditModal.vue
  frontend/src/views/main/component/BookmarkAddModal.vue
Labels: :computer:BE, :computer:FE
